module.exports = (robot) ->

    quote = [
        "This whole creation is essentially subjective, and the dream is the theater where the dreamer is at once scene, actor, prompter, stage manager, author, audience, and critic.",
        "Emotion is the chief source of all becoming-conscious. There can be no transforming of darkness into light and of apathy into movement without emotion.",
        "The secret is that only that which can destroy itself is truly alive.",
        "Our blight is ideologies — they are the long-expected Antichrist!",
        "The wise man who is not heeded is counted a fool, and the fool who proclaims the general folly first and loudest passes for a prophet and Führer, and sometimes it is luckily the other way round as well, or else mankind would long since have perished of stupidity.",
        "We know as little of a supreme being as of Matter. But there is as little doubt of the existence of a supreme being as of Matter. The world beyond is reality, and experiential fact. We only don't understand it.",
        "Even if the whole world were to fall to pieces, the unity of the psyche would never be shattered. And the wider and more numerous the fissures on the surface, the more the unity is strengthened in the depths.",
        "If one does not understand a person, one tends to regard him as a fool.",
        "Nature must not win the game, but she cannot lose. And whenever the conscious mind clings to hard and fast concepts and gets caught in its own rules and regulations - as is unavoidable and of the essence of civilized consciousness - nature pops up with her inescapable demands.",
        "When one is not understood one should as a rule lower one’s voice, because when one really speaks loudly enough and is not heard, it is because people do not want to hear. One had better begin to mutter to oneself, then they get curious.",
        "When we assume God to be a guiding principle—well, sure enough, a god is usually characteristic of a certain system of thought or morality. For instance, take the Christian God, the summum bonum: God is love, love being the highest moral principle; and God is spirit, the spirit being the supreme idea of meaning. All our Christian moral concepts derive from such assumptions, and the supreme essence of all of them is what we call God",
        "Seldom, or perhaps never, does a marriage develop into an individual relationship smoothly and without crises; there is no coming to consciousness without pain.",
        "The growth of the mind is the widening of the range of consciousness, and … each step forward has been a most painful and laborious achievement.",
        "The meeting of two personalities is like the contact of two chemical substances: if there is any reaction, both are transformed.",
        "For it all depends on how we look at things, and not on how they are in themselves. The least of things with a meaning is worth more in life than the greatest of things without it.",
        "The meaning and design of a problem seem not to lie in its solution, but in our working at it incessantly.",
        "No psychic value can disappear without being replaced by another of equivalent intensity.",
        "In all chaos there is a cosmos, in all disorder a secret order.",
        "If there is anything that we wish to change in the child, we should first examine it and see whether it is not something that could better be changed in ourselves.",
        "The conscious mind allows itself to be trained like a parrot, but the unconscious does not — which is why St. Augustine thanked God for not making him responsible for his dreams.",
        "The bigger the crowd, the more negligible the individual.",
        "You can take away a man's gods, but only to give him others in return.",
        "Without consciousness there would, practically speaking, be no world, for the world exists as such only in so far as it is consciously reflected and considered by a psyche. Consciousness is a precondition of being.",
        "Reason alone does not suffice.",
        "As far as we can discern, the sole purpose of human existence is to kindle a light in the darkness of mere being.",
        "Called or uncalled, God will be present.",
        "You are what you do, not what you say you’ll do.",
        "Until you make the unconscious conscious, it will direct your life, and you will call it fate.",
        "I am not what happened to me, I am what I choose to become.",
        "If a man knows more than others, he becomes lonely",
        "Every form of addiction is bad, no matter whether the narcotic be alcohol, morphine or idealism.",
        "We cannot change anything unless we accept it.",
        "None of us stands outside humanity’s black collective shadow.",
        "In sterquiliniis invenitur – in filth it shall be found",
        "What can a man say about woman, his own opposite? I mean of course something sensible, that is outside the sexual program, free of resentment, illusion, and theory. Where is the man to be found capable of such superiority? Woman always stands just where the man’s shadow falls, so that he is only too liable to confuse the two. Then, when he tries to repair this misunderstanding, he overvalues her and believes her the most desirable thing in the world.",
        "No man can converse with an animus for five minutes without becoming the victim of his own anima.",
        "Show me a sane man and I will cure him for you.",
        "There is no coming to consciousness without pain.",
        "The pendulum of the mind alternates between sense and nonsense, not between right and wrong.",
        "Knowledge rests not upon truth alone, but upon error also.",
        "Shame is a soul eating emotion.",
        "The least of things with a meaning is worth more in life than the greatest of things without it",
        "The greatest and most important problems of life are all fundamentally insoluble. They can never be solved but only outgrown.",
        "Nothing has a stronger influence psychologically on their environment and especially on their children than the unlived life of the parent.",
        "Often the hands will solve a mystery that the intellect has struggled with in vain",
        "Primitive superstition lies just below the surface of even the most tough-minded individuals, and it is precisely those who most fight against it who are the first to succumb to its suggestive effects.",
        "Naturally, every age thinks that all ages before it were prejudiced, and today we think this more than ever and are just as wrong as all previous ages that thought so. How often have we not seen the truth condemned! It is sad but unfortunately true that man learns nothing from history.",
        "The wise man who is not heeded is counted a fool, and the fool who proclaims the general folly first and loudest passes for a prophet and Führer, and sometimes it is luckily the other way round as well, or else mankind would long since have perished of stupidity.",
    ]

    robot.hear /jung/i, (res) ->
        res.send(quote[Math.floor(Math.random()* quote.length)])